[alembic]
script_location = alembic/versions
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql://mythos:mythos123@localhost:5432/mythos_safe

[loggers]
keys = root

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(asctime)s] %(name)s: %(message)s
datefmt = %H:%M:%S